.TH SPOCPGET 1 "October 2003"
.\"
.SH NAME
spocpget \- Tool that allows you to list policy rules stored by a SPOCP server
.SH SYNOPSIS
.TP 8
\fBspocpget\fR \fB-s\fR \fIspocp_server\fR \fB-f\fR \fIrule_file\fR
.br
 [\fB-d\fR] [\fB-a\fR \fIsubject_definition\fR]
.br
.TP 8
\fBspocpget\fR \fB-t\fR \fB-s\fR \fIspocp_server\fR \fB-f\fR \fIrule_file\fR
.br
[\fB-d\fR] [\fB-a\fR \fIsubject_definition\fR]
.br
\fB-c\fR \fIcertificate_file\fR \fB-p\fR \fIprivate_key\fR \fB-l\fR \fIca_list\fR
.SH DESCRIPTION
.SS Listing policy rules
.B spocpget
is a small utility that allows you to efficiently list 
rules in a SPOCP server.
.PP
.SH OPTIONS
.TP 12
.IP "\fB-d \fR" 
Turn debugging on.
.IP "\fB-s \fIspocp_server\fR"
Specifies which server you want to talk to. This is either of the form
"server:port" or a unix domain socket name.
.IP "\fB-f \fIrule_file\fR"
Where the rules will be written. If no \fIrule_file\fR is given it will be written
to standard out.
.IP "\fB-a \fIsubject_definition\fR"
In some cases only certain subjects are allowed to list certain types
of rules. This allows you to specify who you act as.
.IP "\fB-c \fIcertificate_file\fR"
Where this hosts certificate is situated. This option is only valid in conjunction
with the \fB-t\fR option.
.IP "\fB-p \fIprivate_key\fR"
Where this hosts private key is situated. This option is only valid in conjunction
with the \fB-t\fR option.
.IP "\fB-l \fICA_list\fR"
The list of trusted CAs. This option is only valid in conjunction
with the \fB-t\fR option.
.PP
.SH EXAMPLES
.PP
.SH SEE ALSO
.BR spocpput (1),
.BR spocptest (1),
.BR spocppatch (1),
.BR spocp (8)
.SH AUTHOR
Roland Hedberg ( roland@catalogix.se )
.RE
.PP
