Document: spocp
Title: Debian spocp Manual
Author: <insert document author here>
Abstract: This manual describes what spocp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/spocp/spocp.sgml.gz

Format: postscript
Files: /usr/share/doc/spocp/spocp.ps.gz

Format: text
Files: /usr/share/doc/spocp/spocp.text.gz

Format: HTML
Index: /usr/share/doc/spocp/html/index.html
Files: /usr/share/doc/spocp/html/*.html

  
